image:
  file: .gitpod.dockerfile
tasks:
  - name: Configure exercism
    command: exercism configure --token=$EXERCISM_TOKEN -w /workspace/exercism
  - name: Install Go staticcheck
    command: go install honnef.co/go/tools/cmd/staticcheck@latest
  - name: Install Go revive
    command: go install github.com/mgechev/revive@latest
  - name: Upgrade sdkman iteself
    command: sdk selfupdate
  - name: SDK upgrade
    command: sdk update && sdk upgrade

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
    - vscjava.vscode-java-pack
    - redhat.java
    - davidanson.vscode-markdownlint
    - golang.go

jetbrains:
  intellij:
    plugins:
         - com.shuzijun.markdown-editor
